#+title:englishLearner

* used to  useage
** habitual actions
subject + used to + (present form of verb [v1])
*** example
I USED TO PLAY (adevadini)
** used to + ing form  (alavatu ayipoyindi)
*** I am USED TO GETTING UP
** nagative
I was not used to getting up early
I was not used to walk
we had to be in a vilage.we were not used to living in a village.
** got used to ( alavatu paddanu )
I GOT USED to  walk.
** get used to ( alavatu chesuko )
*** example
get used to walk (nadavadam alavatu chesuko )
get used to speak in language
get used to it.
you will get used to it ( nuvvu daniki  alavatu ayipothavuley )

* say like to this if anything interrepted when being in the call or in middle of the conversation
** Say, “I am terribly sorry for interrupting” and then something like this;

> “Please continue”
> “Where were we?”
> “Please go on”

*Informal
> "go ahead"

* linking words
** contradicting
*** on the contrary ( opposite to given sentence )
**** she is not lazy. she works extremely hard
A: Did't you find the film exciting
B: ON THE CONTRARY I nearly fell asleep!
** BUT phrases, 'However, on the other hand, still , neverthless etc'
*** examples
Rajesh is in love with Pranavi however.Pranavi is in love with Suresh.
Everyone thought that she would accept the offer.Nevertheless she turned  it down.
I don't want to be late for the meeting. On the other hand, I don't want to get there too early.
** is that why = ( andukena ?/ andukana  )
is the that why you haven't called me?
** besides = (adikaaka)
Do you play any other sports besides basketball?
** that's  that = (adi anthe/ anthe)
I won't agree to it and that's that ( = I won't discuss it any longer )
